#!/usr/bin/env python3

import os
import sys
import random
import time

try:
    n = int(sys.argv[1])
except ValueError:
    sys.exit(1)
    
if (n < 120 or n > 180):
    sys.exit(1)
    
operations = ['+', '-', '*', '/']

for _ in range(n):
    x = random.randint(1, 9)
    o = random.choice(operations)
    y = random.randint(1, 9)
    print(f'{x} {o} {y}', flush=True)
    time.sleep(1)
    
sys.exit(0)

