#!/usr/bin/env python3

import os
import sys
import time
import random

pid = os.getpid()
ppid = os.getppid()

print('Minion[{0}]: created. Parent PID {1}.'.format(pid, ppid))

time_to_sleep = int(sys.argv[1])
time.sleep(time_to_sleep)

status_code = random.choice([0, 1])

print('Child[{0}]: before terminated. Parent PID {1}. Exit status <{2}>'.format(pid, ppid, status_code))

sys.exit(status_code)
